# site settings
title: Courtney A. Jimenez
email: courtneyannjimenez@gmail.com
description: >
  Dartmouth College
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://courtneyannjimenez.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: courtajimenez

# build settings
markdown: kramdown
theme: minima
gems:
   - jekyll-feed
exclude:
   - Gemfile
   - Gemfile.lock
