# Site settings
title: Courtney A. Jimenez
email: courtneyannjimenez@gmail.com
description: >
  Dartmouth College
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://courtneyannjimenez.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: courtajimenez
github_username:  courtneyannjimenez

# Build settings
markdown: kramdown
theme: minima
plug-ins:
  - jekyll-feed

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
   - Gemfile
   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
